#!/bin/bash
#$ -cwd
#$ -V
#$ -S /bin/bash
#$ -l h_rt=4:00:00,vf=500M
# starting and ending indices of identical jobs to run:
#$ -t 1-25
# max number of jobs at any one time:
#$ -tc 25
#$ -e err.txt
#$ -o out.txt
#$ -m eas
#$ -M mabrams@uab.edu

echo -n 'start: ' 1>&2 ; date 1>&2
echo -n 'start: '      ; date

cd $HOME/coh/popco
time sbcl --load start --eval '(defun report-progress-to-console () )' --load crime/crime2c2pundits.lisp

echo -n 'end: ' 1>&2 ; date 1>&2
echo -n 'end: '      ; date
