#!/bin/sh
# Runs POPCO with lisp filename arguments passed to SBCL to be loaded

loadargs=''

# While there are remaining command line arguments which end in ".lisp",
# (i.e. such that stripping off ".lisp" does not produce a different string)
# take arguments off the command line and store them in loadargs, each
# preceded by "--load" in order to tell sbcl what to do with the filenames.
# Remaining args will be left in $@, and accessible in SBCL via *posix-argv*.
while [ "$1" != "${1%.lisp}" ]; do
	loadargs="$loadargs --load $1"
	shift
done

echo "Running popco with SBCL optimizations."
echo "This will have no effect on fasl's compiled without optimizations."
set -x
sbcl --eval '(declaim (optimize (space 0) (speed 3)))' --load start $loadargs "$@"
