# plotRAs.R
# Routines for plotting popco data from arrays generated by routines in df2ra.R

# make a sequence of colors to be used by all plotting functions
maxcolors = 40000  # should be more than the number of lines we might plot
mycolors = rgb(runif(maxcolors),runif(maxcolors),runif(maxcolors))

# This is a transparent gray for shading part of a plot
bgray <- rgb(190, 190, 190, alpha=80, maxColorValue=255) # alph 0 = fully transparent; 180 = opaque (?)


